#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libXdmcp
Version  : 1.1.2
Release  : 8
URL      : http://xorg.freedesktop.org/releases/individual/lib/libXdmcp-1.1.2.tar.bz2
Source0  : http://xorg.freedesktop.org/releases/individual/lib/libXdmcp-1.1.2.tar.bz2
Summary  : X Display Manager Control Protocol library
Group    : Development/Tools
License  : MIT-Opengroup
Requires: libXdmcp-lib
Requires: libXdmcp-doc
BuildRequires : libxslt-bin
BuildRequires : pkgconfig(xorg-macros)
BuildRequires : pkgconfig(xproto)
BuildRequires : xmlto

%description
libXdmcp - X Display Manager Control Protocol library
All questions regarding this software should be directed at the
Xorg mailing list:

%package dev
Summary: dev components for the libXdmcp package.
Group: Development
Requires: libXdmcp-lib
Provides: libXdmcp-devel

%description dev
dev components for the libXdmcp package.


%package doc
Summary: doc components for the libXdmcp package.
Group: Documentation

%description doc
doc components for the libXdmcp package.


%package lib
Summary: lib components for the libXdmcp package.
Group: Libraries

%description lib
lib components for the libXdmcp package.


%prep
%setup -q -n libXdmcp-1.1.2

%build
export LANG=C
%configure --disable-static
make V=1  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/X11/Xdmcp.h
/usr/lib64/libXdmcp.so
/usr/lib64/pkgconfig/xdmcp.pc

%files doc
%defattr(-,root,root,-)
%doc /usr/share/doc/libXdmcp/*

%files lib
%defattr(-,root,root,-)
/usr/lib64/libXdmcp.so.6
/usr/lib64/libXdmcp.so.6.0.0
