#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libXdmcp
Version  : 1.1.2
Release  : 9
URL      : http://xorg.freedesktop.org/releases/individual/lib/libXdmcp-1.1.2.tar.bz2
Source0  : http://xorg.freedesktop.org/releases/individual/lib/libXdmcp-1.1.2.tar.bz2
Summary  : X Display Manager Control Protocol library
Group    : Development/Tools
License  : MIT-Opengroup
Requires: libXdmcp-lib
Requires: libXdmcp-doc
BuildRequires : gcc-dev32
BuildRequires : gcc-libgcc32
BuildRequires : gcc-libstdc++32
BuildRequires : glibc-dev32
BuildRequires : glibc-libc32
BuildRequires : libxslt-bin
BuildRequires : pkgconfig(32xorg-macros)
BuildRequires : pkgconfig(32xproto)
BuildRequires : pkgconfig(xorg-macros)
BuildRequires : pkgconfig(xproto)
BuildRequires : xmlto

%description
libXdmcp - X Display Manager Control Protocol library
All questions regarding this software should be directed at the
Xorg mailing list:

%package dev
Summary: dev components for the libXdmcp package.
Group: Development
Requires: libXdmcp-lib
Provides: libXdmcp-devel

%description dev
dev components for the libXdmcp package.


%package dev32
Summary: dev32 components for the libXdmcp package.
Group: Default
Requires: libXdmcp-lib32

%description dev32
dev32 components for the libXdmcp package.


%package doc
Summary: doc components for the libXdmcp package.
Group: Documentation

%description doc
doc components for the libXdmcp package.


%package lib
Summary: lib components for the libXdmcp package.
Group: Libraries

%description lib
lib components for the libXdmcp package.


%package lib32
Summary: lib32 components for the libXdmcp package.
Group: Default

%description lib32
lib32 components for the libXdmcp package.


%prep
%setup -q -n libXdmcp-1.1.2
pushd ..
cp -a libXdmcp-1.1.2 build32
popd

%build
export LANG=C
%configure --disable-static
make V=1  %{?_smp_mflags}

pushd ../build32
export CFLAGS="$CFLAGS -m32"
export CXXFLAGS="$CXXFLAGS -m32"
%configure --disable-static  --libdir=/usr/lib32
make V=1  %{?_smp_mflags}
popd
%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
rm -rf %{buildroot}
pushd ../build32
%make_install32
if [ -d  %{buildroot}/usr/lib32/pkgconfig ]
then
pushd %{buildroot}/usr/lib32/pkgconfig
for i in *.pc ; do mv $i 32$i ; done
popd
fi
popd
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/X11/Xdmcp.h
/usr/lib64/libXdmcp.so
/usr/lib64/pkgconfig/xdmcp.pc

%files dev32
%defattr(-,root,root,-)
/usr/lib32/libXdmcp.so
/usr/lib32/pkgconfig/32xdmcp.pc

%files doc
%defattr(-,root,root,-)
%doc /usr/share/doc/libXdmcp/*

%files lib
%defattr(-,root,root,-)
/usr/lib64/libXdmcp.so.6
/usr/lib64/libXdmcp.so.6.0.0

%files lib32
%defattr(-,root,root,-)
/usr/lib32/libXdmcp.so.6
/usr/lib32/libXdmcp.so.6.0.0
